--- Icons
return {
    log = {
        TRACE = '',
        DEBUG = 'ﴫ',
        INFO  = '',
        WARN  = '',
        ERROR = '',
        OFF   = '',
    },
    todo = {
        FIX  = '',
        TODO = '',
        HACK = '',
        WARN = '',
        PERF = '',
        NOTE = '',
    },
    git = {
        status = {
            A = '落',
            C = 'ﭡ',
            D = '',
            M = 'ﱴ',
            R = '',
            T = '',
            U = 'ﭦ',
            X = 'ﬤ',
        },
        hunks = {
            A = '',
            D = '',
            I = '',
            M = '',
        }
    },
    cmp = {
        buffer   = '﬘',
        git      = '',
        nvim_lsp = '',
        omni     = '',
        path     = 'ﱮ',
        snippy   = '',
    },
    lsp = {
        kind = {
            Array         = '',
            Boolean       = '',
            Class         = 'ﴯ',
            Color         = '',
            Constant      = '',
            Constructor   = '',
            Enum          = '',
            EnumMember    = 'ϵ',
            Event         = '',
            Field         = '',
            File          = '',
            Folder        = '',
            Function      = '',
            Interface     = '',
            Key           = '',
            Method        = '',
            Module        = '',
            Namespace     = 'ﮟ',
            Number        = '',
            Null          = 'ﳠ',
            Object        = '',
            Operator      = '',
            Property      = '',
            Reference     = '',
            Snippet       = '',
            String        = '',
            Struct        = '',
            Text          = '',
            TypeParameter = '𝙏',
            Unit          = '',
            Value         = '',
            Variable      = '',
        },
        diag = {
            Error = '',
            Warn  = '',
            Hint  = '',
            Info  = '',
        },
        hint = 'ﯦ'
    }
}
